### ISSUE TITLE
Update website when the library is updated

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs#102]
At the moment we are working with two repositories:

- Library (this repo): https://github.com/Nautilus-Cyberneering/chinese-ideographs
- Website: https://github.com/Nautilus-Cyberneering/chinese-ideographs-website

The website is using a git submodule to import this library. It has a scheduled workflow ([import-base-images.yml](https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/blob/main/.github/workflows/import-base-images.yml)) which:

1. updates the library
2. pulls the latest Base images from the dvc remote storage
3. creates a JPEG version of the images
4. auto-commit them into the website repo.

We want to improve this process by triggering the workflow only when the library has Base image changes.

The idea is to trigger the workflow on the website every time the library changes (on every main branch push event).

The implementation could be something like this:

```
- name: Invoke workflow in another repo with inputs
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: Import Base images from remote media library
    repo: Nautilus-Cyberneering/chinese-ideographs-website
    token: ${{ secrets.PERSONAL_TOKEN }}
    inputs: '{ "library_sha": "378acd13e3a98a39a231d0f2ff35a4f885ce3d6c" }'
```

If we use an action from the marketplace: https://github.com/marketplace/actions/workflow-dispatch
