### ISSUE TITLE
Replace "Validate filenames" step by the Librarian

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs#134]
In the [Gold Drawing Processing Workflow](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/.github/workflows/gold-drawings-processing.yml) we have a step to validate media filenames:

```
- name: Validate filenames
  uses: ./.github/actions/validate-filenames
  with:
    filenames: ${{ steps.dvc-diff.outputs.diff }}
```

We have moved that login to the Librarian, but It's still pending to merge: https://github.com/Nautilus-Cyberneering/librarian/pull/28
As soon as we merge it we can replace the action with the Librarian comman:

```
nautilus-librarian gold-drawing-processing DVC_DIFF
```

The command expects the dvc output. @yeraydavidrodriguez is also working on adding that setp (dvc-diff to the `gold-drawing-processing`). Once he finishes we can also remove the previous step and the argument for the command.
