### ISSUE TITLE
Execute `Gold Drawings Processing` workflow only when there are library changes

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs#154]
I think we could add a "path" filter to the workflow in order to execute it only when the library has changed.

```yml
name: Gold Drawings Processing

on:
  pull_request:
    branches: [main, issue-*]
    paths:
      - 'data/**'
  workflow_dispatch:
```
