### ISSUE TITLE
GitHub Action: Generate Base image from Gold tiff image

### ISSUE THREAD

**Issue by cgbosse** [Nautilus-Cyberneering/chinese-ideographs#16]
In the Gold Image Processing workflow we need to add a new step to generate Base images from Gold version.

The current workflow has:

```
name: Gold Drawings Processing

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.

      - name: DVC diff
        id: dvc-diff
        uses: ./.github/actions/dvc-diff
        env:
          DVC_REPO_DIR: ${{ github.workspace }}
          PREVIOUS_REF: ${{ github.base_ref }}
          CURRENT_REF: ${{ github.head_ref }}

      - name: Validate filenames
        if: steps.dvc-diff.outputs.diff != '{}'
        uses: ./.github/actions/validate-filenames
        with:
          filenames: ${{ steps.dvc-diff.outputs.diff }}
```

Basically, get the list of changed images (added or updated) using dvc, then we validate the filenames, and the next step is Base image generation.

We have to create a new GitHub Action and also a new section in the documentation folder describing this new artifact.
