### ISSUE TITLE
GitHub Action: validate Gold Image folder

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs#47]
We have to add a new step to the `Gold Drawings Processing` workflow. When the artist adds or updates a Gold Image we have to check if the image is in the right folder.  Right now the folder structure is very simple. You can read the [documentation](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/documentation/Filenames_and_Folder_Structure_Conventions.md#image-folder-structure).

This is the basic structure:

```
data/
├── 000001
│   ├── 32 (gold images)
│   │   └── 000001-32.600.2.tif
│   └── 42 (base images)
│   │   └── 000001-42.600.2.tif
└── README.md
```

Inputs: the list of added/updated images (from `dvc-diff` output)
Output: exception if we found a file in the wrong place.

We can implement it very similar to what we did for filename validation.

Tasks:

- We have to identify Gold Images in the dvc-diff output.
- We have to extract the `artwork_id` from the filename.
- We have to extract the `purpose_code` from the filename.
- We have to build the full path for the expected filepath.
- Check if the expected and actual paths match.

[Documentation for filename format and folder structure](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/documentation/Filenames_and_Folder_Structure_Conventions.md#filenames-and-folder-structure-conventions).

**Comment by josecelano** [comment]
I'm having problem to run the job locally with `act`.

If I try to execute the workflow locally with `act pull_request --job build` the `diff` output variable is not passed to the next step:

```
[Gold Drawings Processing/build] ⭐  Run DVC diff
[Gold Drawings Processing/build]   🐳  docker run image=act-github-actions-dvc-diff:latest platform= entrypoint=[] cmd=[]
| dvc diff --show-json HEAD 
::set-output name=diff::{"added": [], "deleted": [], "modified": [], "renamed": [], "not in cache": [{"path": "data/000001/32/000001-32.600.2.tif"}]}
| {"added": [], "deleted": [], "modified": [], "renamed": [], "not in cache": [{"path": "data/000001/32/000001-32.600.2.tif"}]}
[Gold Drawings Processing/build]   ✅  Success - DVC diff
[Gold Drawings Processing/build] ⭐  Run Debug diff ouput
[Gold Drawings Processing/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /home/josecelano/Documents/github/Nautilus-Cyberneering/chinese-ideographs/workflow/6] user=
| The diff output is: 
[Gold Drawings Processing/build]   ✅  Success - Debug diff ouput
```

But it works on the runner: https://github.com/Nautilus-Cyberneering/chinese-ideographs/runs/3859082823?check_suite_focus=true#step:8:7

I'm going to try using the full act docker image: ghcr.io/catthehacker/ubuntu:full-latest

**Comment by josecelano** [comment]
It seems it could be an `act` bug: https://github.com/nektos/act/issues/758 although that issue is using two jobs and I'm using only one job. I tested with this sample workflow:

```
name: Gold Drawings Processing

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.

      - id: set_1
        run: |
          echo "::set-output name=var_1::$(echo hello)"

      - id: set_2
        run: |
          echo "::set-output name=var_2::$(echo world)"

      - name: DVC diff
        id: dvc-diff
        uses: ./.github/actions/dvc-diff
        env:
          DVC_REPO_DIR: "${{ github.workspace }}"
          PREVIOUS_REF: HEAD
          CURRENT_REF:

      - name: Debug diff ouput
        run: |
          echo "The diff output is: ${{ steps.set_1.outputs.var_1 }}"
          echo "The diff output is: ${{ steps.set_2.outputs.var_2 }}"
          echo "The diff output is: ${{ steps.dvcdiff.outputs.diff }}"
```

And it does not work. So I think it's a new `act` bug. It could only happen when the next step is an action. I'm going to create a new repo and try to reproduce the error in order to submit a new bug to `act.
