### ISSUE TITLE
GitHub Action: Add Base image to the repository

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs#70]
This is the current workflow to process Gold Images:

```
name: Gold Drawings Processing

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.
      - name: Debug env vars
        ...
      - name: Set env (runner)
        ...
      - name: Git diff
        ...
      - name: DVC diff
        id: dvc-diff
        uses: ./.github/actions/dvc-diff
        env:
          DVC_REPO_DIR: "${{ github.workspace }}"
       ...
      - name: Validate filenames (runner)
        if: ${{ !env.ACT }}
        uses: ./.github/actions/validate-filenames
        with:
          filenames: ${{ steps.dvc-diff.outputs.diff }}
        ...
      - name: Validate Gold images folder (runner)
        if: ${{ !env.ACT }}
        uses: ./.github/actions/validate-gold-image-folder
        with:
          filepaths: ${{ steps.dvc-diff.outputs.diff }}

```

Basically, we find out what are the changed Gold Images (added or updated), we validate the filenames and the folder where the images are. @yeraydavidrodriguez is working on generating the Base image (change colour space profile and resize).

There are two main steps missing:

1. Add the Base image to DVC remote storage (dvc add and dvc push) and auto-commit changes (add the dvc pointer in the git repo)
2. Trigger a workflow on the website repo https://github.com/Nautilus-Cyberneering/chinese-ideographs-website. For the time being, we are going to use a polling strategy. The website is going to pull new Base images every day from this repo.

This issue is for the auto-commit action. We need a GitHub Action like this:

```
      - name: Auto-commit Base image
        uses: ./.github/actions/auto-commit-base-image
        with:
          filepaths: ${{ steps.resize-image.outputs.filepaths }}
```

The input is a list of Base images (`filepaths`). The input format could be like this:

```
{
   "added":[
      {
         "path":"data/000001/42/000001-42.600.2.tif"
      }
   ],
   "deleted":[
   ],
   "modified":[
   ],
   "renamed":[
   ]
}
```

It's the same format we use for the `dvc-diff` action. Maybe the `resize-image` action could have an output with this format. So we can chain the output of the previous step with the input of this one. For the POC we are not considering yet rename/delete. If we detect deleted Gold images we should delete the corresponding Base image and use this action to commit that change.

Requirements:

- We agreed on adding only one change for each commit. That means if we have two new Base images we are going to create two different commits following the same convention as for PR: https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/documentation/Gold_Images.md#creating-a-pr-to-add-or-update-gold-images
- In the future, this action could be also used to commit new Gold images when you create a PR. I mean, the process it's pretty similar.

Tasks:

1. `dvc add BASE_IAMGE.tif`: add Base image to dvc
2. `dvc push`: push Base image to remote storage
3. `git add BASE_IMAGE.tif.dvc and .gitignore`: add dvc changes to git
4. `git commit -m "Add Base Image: 000001-42.600.2.tif"`
5. `git push`: add Base image info to the repo

We have to repeat that process for every image on the input variable (`filepaths`).

I do not know if in this case we can just build a bash wrapper for dvc and git (like dvc-diff action) or it makes sense to use a Python wrapper since I expect this action to have more data manipulation.
